# Generated by Django 4.2.6 on 2023-10-28 21:22

from django.db import migrations, models
import django_cpf_cnpj.fields
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('address', models.CharField(max_length=255)),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, max_length=9, null=True)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='user_files')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
